# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6653e4da307950ab3ed120a005124e5d8e255283c18f3417332c62951e47deb7186a3b06fe681ba7c4c5d4d56abe34f6a38a3fe4a19fa42c7b02e4e58ff3acd1

test:
  secret_key_base: 957590aae64978e9146a18c5d65a61300c584c8280f3d870c867e86f6a98bc9f0617b53ca238a5d2193b88f9adbd50382288eb51fe6b4d6aa8dc21f026140e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
